FROM grafana/grafana:6.7.0
COPY report.json /etc/grafana/provisioning/dashboards/home.json
COPY dashboard.yaml /etc/grafana/provisioning/dashboards
COPY datasource.yaml /etc/grafana/provisioning/datasources
